telegram:
  task-service:
    url: "http://localhost:8083"
  futurity:
    url: https://cfca-93-170-64-106.ngrok-free.app

spring:
  rabbitmq:
    username: alex
    password: password
    addresses: localhost:5672
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    show-sql: true
